---
- name: Caddy Builds on Soleil (Weekly Cron)
  hosts: core
  tasks:
    - name: Do the thing
      ansible.builtin.command: xcaddy build --with github.com/caddy-dns/rfc2136@master --with github.com/mholt/caddy-ratelimit --output /var/www/caddy-build/bin
      register: out
      changed_when: out.rc != 0
    - name: Print output of thing
      ansible.builtin.debug:
        var: out.stderr_lines
