# IMPORTANT: Inventory file for pubnix is stored in semaphore, not inventory.yml
---
- name: Caddy Builds on Pubnix (Weekly Cron)
  hosts: pubnix
  tasks:
    - name: Do the thing
      ansible.builtin.command: bash -c 'xcaddy build --with github.com/aksdb/caddy-cgi/v2@master --output /tmp/caddy && mv /tmp/caddy /usr/local/bin'
      register: out
      changed_when: out.rc != 0
    - name: Print output of thing
      ansible.builtin.debug:
        var: out.stderr_lines
