---
- name: Caddy Builds on IN Node (Weekly Cron)
  hosts: in
  tasks:
    - name: Do the thing
      ansible.builtin.command: xcaddy build --with github.com/caddy-dns/rfc2136@master --with github.com/gi-yt/ratelimit@master --output /var/www/caddy-build/api/download
      register: out
      changed_when: out.rc != 0
    - name: Print output of thing
      ansible.builtin.debug:
        var: out.stderr_lines
