---
- name: Hourly Restarts (ALL NODES)
  hosts: privfrontends
  vars:
    services:
      - invidious-invidious-1
      - breezewiki
      - anonymousoverflow
      - mozhi
      - redlib
      - teddit
      - nitter
  tasks:
    - name: Do thing
      ansible.builtin.command: docker restart {{ item }}
      register: out
      changed_when: out.rc != 0
      with_items: "{{ services }}"
