---
- name: Docker Prunes (Daily Cron)
  hosts: privfrontends
  tasks:
    - name: Do thing
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        timeout: 1000
