---
- name: Docker Prunes (Daily Cron)
  hosts: privfrontends
  tasks:
    - name: Do thing
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        timeout: 1000
- hosts: in
  tasks:
    - name: Run fstrim (IN Node)
      ansible.builtin.command: fstrim -av
      register: out
      changed_when: out.rc != 0
