---
bkp_source_directories:
  - /var
  - /home
  - /opt/docker/minio/hdd
  - /boot
  - /usr
  - /root
  - /opt
  - /zfspool
  - /etc
bkp_exclude_patterns:
  - /var/log
  - /var/lib/docker/buildkit
  - /var/lib/docker/containers
  - /var/lib/docker/image
  - /var/lib/docker/overlay2
  - /var/lib/docker/plugins
  - /var/lib/docker/runtimes
  - /var/lib/docker/swarm
  - /var/lib/docker/tmp
  - /var/lib/docker/trust
  - /var/lib/postgresql
bkp_postgresql_databases:
  - name: authentik
  - name: ejabberd
  - name: ente
  - name: freshrss
  - name: gitea
  - name: healthchecks
  - name: hedgedoc
  - name: invin
  - name: mailu
  - name: piped
  - name: postgres
  - name: roundcube
  - name: semaphore
  - name: synapse
  - name: vaultwarden
  - name: wikijs
