- name: Docker
  hosts: in
  vars_files:
    - ./vars.yaml
  tasks:
    - name: Deploy stack role
      ansible.builtin.include_role:
        name: gi-yt.docker_compose_declarative
      vars:
        app: "{{ item.value }}"
        app_name: "{{ item.key | lower }}"
        configs_dir_local: "./configs/{{ item.key }}"
      loop: "{{ apps.groups | default({}) | dict2items }}"
      when: item.value.docker_settings
